//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using XnaGeometry;
using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.Threading;


namespace AssemblyCSharp
{
	//[RequireComponent(typeof(NavMeshAgent))]

	//Stores information about a agent's pathfinding requests
	public class PathFindingRecord /*: MonoBehaviour*/
	{

		public Vector3 start;
		public Vector3 destination;
		public int ID = 0;

		public PathFindingRecord(int ID){
			this.ID = ID;
			destination = new Vector3 (float.PositiveInfinity, float.PositiveInfinity, float.PositiveInfinity);
		}
		
	}
}

