//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;



namespace AssemblyCSharp
{
	/*
	 * Generic class allowing for the loading, saving, and editing of any class supporting editor view
	 * 
	 */
	public class LSEEditor<T> where T: class,EditorDisplay
	{
		T instanceToEdit = null;

		string fileToLoadTreeFrom = "default_q_File";
		string fileToSaveTreeTo = "default_q_File_sv";

		Vector2 scrollPos = Vector2.zero;

		public void LoadWindow(){

			if (GUILayout.Button ("Load")) {
				T tempCL = null;
				if (Utils.DeserializeFile<T> (fileToLoadTreeFrom, ref tempCL) && tempCL != null) {
					instanceToEdit = tempCL;
				} else {
					Debug.Log ("File could not load!");
				}
			}
		}

		public void SaveWindow(){
			if (GUILayout.Button ("Save")) {
				if (instanceToEdit != null) {
					Utils.SerializeFile (fileToSaveTreeTo, ref instanceToEdit);
				} else {
					Debug.Log ("No instance to save!");
				}
			}
		}

		public void DisplayObjectForEditing(){
			if (instanceToEdit != null) {
				scrollPos = EditorGUILayout.BeginScrollView(scrollPos,true,true);
				instanceToEdit.ToEditorView();
				EditorGUILayout.EndScrollView();
			}
		}

		public T InstanceToEdit {
			get {
				return instanceToEdit;
			}
			set {
				instanceToEdit = value;
			}
		}
	}
}

