//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	//used to map a prefab to a robot type enum value, to tell UI which model to load for the team member
	[Serializable]
	public class RobotPrefabMapping
	{
		public RobotType robotType = RobotType.ASSAULT;
		public GameObject prefabToSpawn;

		public bool Equals(RobotPrefabMapping other){
			return other.robotType == robotType;
		}
	}
}

