//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;


namespace AssemblyCSharp
{
	[Serializable]
	public class SelectionRow
	{
		public int currentlySelected = 0;

		public List<MeshCollider> colliderToHitInOrderToSelect;
		public List<MeshRenderer> meshRendererToEnableUponSelection;
		
		public List<Transform> prefabSpawnPoints;
		
		public TextAsset referenceForPlayerData;
		
		public float scaleForModel = 3f;
		
		RaycastHit hit;
		Ray ray;
	}
}

