//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Weapons
{
	public class HomingRocket : RocketProjectileScript
	{
		public Transform transformToMoveTowards;
		public float steeringRate = 15f;
		
		void Update(){
			direction = Vector3.MoveTowards(direction, transformToMoveTowards.position - gameObject.transform.position, steeringRate*Time.deltaTime);
			direction.Normalize ();
			base.Update ();
		}
	}
}

