//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AI
{
	//Types of results that LOS tests can return
	public enum LOSResult
	{
		Visible,Invisible,PeripheralVisionTriggered
	}
}

