//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AI
{
	[Serializable]
	public class SoldierIntel
	{
		public SoldierEntity soldierEntityToTrack = null; 
		public Vector3 lastKnownPosition = Vector3.zero;//if this is null the soldier position is not known
		public int numTroopsTracking = 0;
		public float TimeWhenIntelWasLastUpdated = 0;
		public Vector3 averageVelocity = Vector3.zero;
		public int numSoldiersAssignedToThisTarget = 0;
		public float lastRayCastAngle = float.PositiveInfinity;
		public Vector3 positionOfLastSoldierToSpotThisSoldier = Vector3.zero;

		public SoldierIntel(SoldierEntity soldierEntityToTrack){
			this.soldierEntityToTrack = soldierEntityToTrack;
		}
	}
}

