//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class FollowCameraController : MonoBehaviour
	{
		Vector3 localPos = Vector3.zero;
		void Update(){
			if (Input.GetKeyDown (KeyCode.C)) {
				localPos = Camera.main.transform.localPosition;
				++QSoldier.currentAgent;
				QSoldier.currentAgent%=QSoldier.allQSensors.Count;
				Camera.main.transform.parent = QSoldier.allQSensors[QSoldier.currentAgent].transform;
				Camera.main.transform.localPosition = localPos;
				Camera.main.transform.LookAt(QSoldier.allQSensors[QSoldier.currentAgent].transform.position);
			}

			if (Input.GetKey (KeyCode.P)) {
				//if (QSoldier.allQSensors[QSoldier.currentAgent] is QConjectureAgent){
					(QSoldier.allQSensors[QSoldier.currentAgent]).Reward(-1f*Time.deltaTime);
				//}
			} else if (Input.GetKey (KeyCode.R)) {
				//if (QSoldier.allQSensors[QSoldier.currentAgent] is QConjectureAgent){
					(QSoldier.allQSensors[QSoldier.currentAgent]).Reward(1f*Time.deltaTime);
				//}
			}

		}
	}
}

