//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class QNNAgent : QAgent
	{
		public List<ActionGroup> actionGroupings = new List<ActionGroup> ();
		public override List<string> GetAction (List<string> state, List<float> values){
			return null;
		}
		

		public override bool RewardAgent (float reward){
			return false;
		}

		public override void Reset(){

		}
	}
}

