//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEngine.UI;


namespace AssemblyCSharp
{
	public class ScoreDisplay : MonoBehaviour
	{
		public Text text;
		public string sideOneName;
		public string sideTwoName;
		void Update(){
			//text.text = sideOneName + " " + GameData.scores [0] + " " + sideTwoName + " " + GameData.scores [1]; 
		}
	}
}

