//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;


namespace AssemblyCSharp
{


	//Base class for all agents that can detect and provide their state to a q learner
	public abstract class QSensor : MonoBehaviour
	{


		public abstract List<string> getState();

		public abstract List<float> getStateValues ();

		public abstract int GetBusyWithAction(); //return number of actions soldier is busy with

		public abstract void Reward(float reward); //need this method to support manual rewards and punishments by the user
	}
}

